#!/bin/bash

# Script to configure the eCAL project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"

# Create build directory if it doesn't exist
if [ ! -d "$BUILD_DIR" ]; then
    echo "Creating build directory: $BUILD_DIR"
    mkdir -p "$BUILD_DIR"
else
    echo "Build directory already exists: $BUILD_DIR"
fi

git submodule init
git submodule update

echo "Configuring project..."
cd "$BUILD_DIR"
cmake "$SCRIPT_DIR" -GNinja \
    -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=cmake/submodule_dependencies.cmake \
    -DECAL_USE_CURL=OFF \
    -DECAL_USE_FTXUI=OFF \
    -DECAL_USE_HDF5=ON \
    -DECAL_USE_QT=OFF \
    -DECAL_USE_CAPNPROTO=OFF \
    -DECAL_USE_FLATBUFFERS=OFF \
    -DECAL_USE_NPCAP=OFF \
    -DBUILD_TESTING=OFF \
    -DECAL_BUILD_DOCS=OFF \ \
    -DECAL_BUILD_APPS=ON \
    -DECAL_BUILD_SAMPLES=ON \
    -DECAL_BUILD_TESTS=OFF \
    -DECAL_BUILD_TIMEPLUGINS=ON \
    -DECAL_BUILD_C_BINDING=OFF \
    -DECAL_BUILD_CSHARP_BINDING=OFF \
    -DECAL_BUILD_PY_BINDING=OFF \
    -DECAL_BUILD_APP_SDK=OFF \
    -DECAL_BUILD_C_BINDING=OFF \
    -DECAL_INSTALL_SAMPLE_SOURCES=OFF  \
    -DECAL_DEPLOY_DEPENDENCIES=OFF \
    -DECAL_CPACK_PACK_WITH_INNOSETUP=OFF \
    -DECAL_THIRDPARTY_BUILD_YAML-CPP=ON \
    -DECAL_THIRDPARTY_BUILD_TCP_PUBSUB=ON \
    -DECAL_THIRDPARTY_BUILD_PROTOBUF=ON \
    -DECAL_THIRDPARTY_BUILD_ASIO=ON \
    -DECAL_THIRDPARTY_BUILD_CURL=OFF \
    -DECAL_THIRDPARTY_BUILD_FINEFTP=ON \
    -DECAL_THIRDPARTY_BUILD_FTXUI=OFF \
    -DECAL_THIRDPARTY_BUILD_RECYCLE=ON \
    -DECAL_THIRDPARTY_BUILD_SPDLOG=ON \
    -DECAL_THIRDPARTY_BUILD_TCLAP=ON \
    -DECAL_THIRDPARTY_BUILD_TINYXML2=ON \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF
